# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 01:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alquileres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechaalquiler',
            name='propiedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alquileres.Propiedad'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alquileres.Ciudad'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fechaReserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alquileres.fechaAlquiler'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='huesped',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alquileres.Huesped'),
        ),
    ]
