# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquileres', '0003_auto_20171111_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='imagen',
            field=models.ImageField(upload_to='http://localhost:8000/media/'),
        ),
    ]
