# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquileres', '0005_auto_20171113_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='imagen',
            field=models.ImageField(upload_to='image'),
        ),
    ]
