# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 01:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alquileres', '0007_auto_20171126_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fechaalquiler',
            name='mail',
        ),
        migrations.AddField(
            model_name='fechaalquiler',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='alquileres.Reserva'),
        ),
    ]
