# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquileres', '0009_auto_20171128_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='precioDiario',
            field=models.IntegerField(),
        ),
    ]
